<a href="https://colab.research.google.com/github/kaziyevshohrux/AI_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:

import pandas as pd

In [ ]:
print(pd.__version__)

2.2.3

In [ ]:

mydataset = {
      'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, 3, 4, 6, 6]
}

df = pd.DataFrame(mydataset) # DataFrame() Dictionary table qilib beradi
print('DataFrame:', df)

DataFrame:       cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       3
4  Ferrari       4
5     Ford       6
6      BMW       6

In [ ]:
df.head(20) # default 5  table boshidan nechta indexni kursatishni belgilaydi

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       3
4  Ferrari       4
5     Ford       6
6      BMW       6

In [ ]:
df.tail() # Tableni oxirgi indexdan boshlab chiqaradi

      cars  counts
2     Ford       2
3    Tesla       3
4  Ferrari       4
5     Ford       6
6      BMW       6

In [ ]:
df.shape # nechta qator rows va nechta ustun columns borligini kursatadi

(7, 2)

In [ ]:

df.columns # nechta ustun borligini ko'rsatadi

Index(['cars', 'counts'], dtype='object')

In [ ]:

df.dtypes # qanday data-typesni kursatadi

cars      object
counts     int64
dtype: object

In [ ]:
df.describe(include='all') # numerical columns only

       cars    counts
count     7  7.000000
unique    5       NaN
top     BMW       NaN
freq      2       NaN
mean    NaN  4.428571
std     NaN  1.902379
min     NaN  2.000000
25%     NaN  3.000000
50%     NaN  4.000000
75%     NaN  6.000000
max     NaN  7.000000

In [ ]:
df.iloc[1:5] # aniq bir indexni malumotini chiqarib beradi

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       3
4  Ferrari       4

In [ ]:
df.loc[:, 'counts'] # aniq bir ustun columnni malumotini ko'rsatadi

0    3
1    7
2    2
3    3
4    4
5    6
6    6
Name: counts, dtype: int64

In [ ]:

df[df['counts'] > 3 ] # condition orqali malumotni chiqaradi

      cars  counts
1    Volvo       7
4  Ferrari       4
5     Ford       6
6      BMW       6

In [ ]:
df[df['cars'] == 'BMW'] # string malumotni chiqaradi

  cars  counts
0  BMW       3
6  BMW       6

In [ ]:
df.mean(numeric_only=True) # o'rtacha valueni chiqarib beradi
df['counts'].mean()

np.float64(4.428571428571429)

In [ ]:
df.sum() # hamma columnni yig'indisini chiqarib beradi

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 31
dtype: object

In [ ]:
df.min()
df.max()
df.median(numeric_only=True) # o'rtacha valueni chiqaradi

counts    4.0
dtype: float64

In [ ]:
df.count() # nechta bo’sh bo’lmagan (non-null) qiymatlar sonini sanaydi

cars      7
counts    7
dtype: int64

In [ ]:
df.std(numeric_only=True) # ma’lumot qanchalik bir xil yoki tarqoq ekanini ko’rsatadi

counts    1.902379
dtype: float64

In [ ]:
data_with_missing = {
    'cars': ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "BMW"],
    'counts': [3, 7, None, 3, None, None, 6]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     3.0
4  Ferrari     NaN
5     None     NaN
6      BMW     6.0

In [ ]:
df_missing.isnull().sum() #null bulganlarni boolean qilib chiqaradi

cars      2
counts    3
dtype: int64

In [ ]:
df_missing.dropna(how='all') # Null bulgan ma'lumotlarni olib tashlayapdi data cleaning

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     3.0
4  Ferrari     NaN
6      BMW     6.0

In [ ]:
df_missing.dropna(subset='cars')

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     3.0
4  Ferrari     NaN
6      BMW     6.0

In [ ]:
df_missing.fillna({'cars': 'unkown', 'counts': 0}) #missing value larga value qoyib chiqadi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2   unkown     0.0
3    Tesla     3.0
4  Ferrari     0.0
5   unkown     0.0
6      BMW     6.0

In [ ]:
df_b = pd.read_csv("Titanic-Dataset.csv")

In [ ]:
df_b.head()


df_b.tail()

#df = pd.read_excel('Titanic-Dataset.xlsx')
#df = pd.read_json('Titanic-Dataset.json')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df_b.to_excel("test.xlsx")

In [ ]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"] )
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [ ]:
car_series = data_with_missing["cars"]
print(car_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'BMW']