<a href="https://colab.research.google.com/github/kaziyevshohrux/AI_foundation/blob/main/studentPerformance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
import pandas as pd
import numpy as np

In [48]:
#df = pd.read_csv("StudentsPerformance.csv")
df = pd.read_csv("studentsPerformance.csv")
print("shape: ",df.shape)
print("colums:" , df.columns.tolist())

print("5 rows in StudentsPerformance  ")

shape:  (1000, 12)
colums: ['Unnamed: 0', 'gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score', 'total score', 'avarge score', 'passed']
5 rows in StudentsPerformance

In [24]:
print(df.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

In [32]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [23]:
print("Summary about full data:")
print(df.describe())

print("info about  : null : in full list ")
print(df.info())

Summary about full data:
       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000
info about  : null : in full list
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [22]:
print("Student who take max score from some columns:")

df[["math score", "reading score", "writing score"]].max()

Student who take max score from some columns:

math score       100
reading score    100
writing score    100
dtype: int64

In [21]:
print("Student who min score:")

df[["writing score", "reading score","math score" ]].min()

Student who min score:

writing score    10
reading score    17
math score        0
dtype: int64

In [27]:
print("Student who avarge score:")

df[["writing score", "reading score","math score" ]].mean()

Student who avarge score:

writing score    68.054
reading score    69.169
math score       66.089
dtype: float64

In [28]:
print("correlation:")   # birini ikkinchisifga bigliqligi tasiri

df[["math score", "reading score", "writing score"]].corr()

correlation:

               math score  reading score  writing score
math score       1.000000       0.817580       0.802642
reading score    0.817580       1.000000       0.954598
writing score    0.802642       0.954598       1.000000

In [29]:
print("create new columns preview (math , reading , writing score) ")

df["total score"] = df[["math score", "reading score", "writing score"]].sum(axis=1)  #create total score
df["avarge score"] = df["total score"] / 3
df["passed"] = np.where(df["avarge score"] >=50, "Yes", "No")

print(df[["total score", "avarge score", "passed"]].head())

create new columns preview (math , reading , writing score)
   total score  avarge score passed
0          218     72.666667    Yes
1          247     82.333333    Yes
2          278     92.666667    Yes
3          148     49.333333     No
4          229     76.333333    Yes

In [56]:
test_prep_group = df.groupby("test preparation course")[["math score", "reading score", "writing score"]].mean()
print("Students avarge score by test preparation:")
print(test_prep_group)


#gender

gender_avg = df.groupby("gender")[["math score", "reading score", "writing score"]].mean()
print("Avarge score by gender")
print(gender_avg)

#passed

passed_rate = df["passed"].value_counts(normalize=True) *100
print("Passed rate")
print(passed_rate)

gender_pass = df.groupby("gender")["passed"].value_counts(normalize=True) * 100
print("Gender passed persenatege")
print(gender_pass)

Students avarge score by test preparation:
                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673
Avarge score by gender
        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203
Passed rate
passed
Yes    89.7
No     10.3
Name: proportion, dtype: float64
Gender passed persenatege
gender  passed
female  Yes       92.471042
        No         7.528958
male    Yes       86.721992
        No        13.278008
Name: proportion, dtype: float64

In [15]:
# Concert scores to Numpy array
scores = df[["math score", "reading score", "writing score"]].values

# Mean , std
print("Numpy mean:" , np.mean(scores, axis=0))
print("Numpy std", np.std(scores, axis=0))

# Z-score (normalize)
# avarge = 0
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-score", z_score[:5])

Numpy mean: [66.089 69.169 68.054]
Numpy std [15.15549666 14.59289002 15.18805728]
Z-score [[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 [-1.25954302 -0.83389925 -1.58374436]
 [ 0.65395415  0.60515772  0.45733301]]

In [31]:
# how many students take best scores

top_scores = df[df["avarge score"] >= 90]
print("Top students score above 90:", len(top_scores))

# how many students are failes

failed_students = df[df["passed"] == "No"]
print("Failed students:" , len(failed_students))

Top students score above 90: 52
Failed students: 103

In [77]:
#practise myself

df.to_csv("studentsPerformance.csv")

male = df[df["gender"] == "male"]
print(len(male))

male_math = df[(df["gender"] == "male") &
               (df["math score"] >= 63)]
print("male passed math :",len(male_math))


female_reading = (
    (df["gender"] == "female") &
    (df["reading score"] >= 70)
).sum()

print("female who passed reading:", female_reading)


male_filter = (
    (df["gender"] == "male") &
    (df["passed"] == "Yes") &
    (df["math score"] >=50)&
    (df["test preparation course"] == "completed")

).sum()
print("filter male:", male_filter)

482
male passed math : 313
female who passed reading: 318
filter male: 158